# These are supported funding model platforms

github: [blastbeng]
custom: ["https://www.paypal.com/donate/?hosted_button_id=W8JMMLVY3G62C"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
