name: spotisub
services:
  spotisub:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: spotisub
    environment:
      - SPOTIPY_CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXX
      - SPOTIPY_CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXX
      - SPOTIPY_REDIRECT_URI=http://127.0.0.1:8080/
      - SUBSONIC_API_HOST=http://127.0.0.1
      - SUBSONIC_API_PORT=4533
      - SUBSONIC_API_USER=user
      - SUBSONIC_API_PASS=pass
    image: "blastbeng/spotisub:latest"
    restart: always
    volumes:
      - "./cache:/home/user/spotisub/cache"
    ports:
      - 5183:5183
    healthcheck:
      test: curl -s http://127.0.0.1:5183/api/v1/utils/healthcheck | grep -q 'Ok!' || exit 1
      interval: 30s
      retries: 20
      start_period: 30s
